import './01_classes';
import './02_for_of';
import './03_shorthands'
import './04_templates'
import './05_default_args'
import './06_let'
import './07_rest_args'
import './08_spread'
import './09_destructured_args'
import './10_arrow_funcs'